"""
GeoData Backend API Server

This FastAPI application provides REST API endpoints for extracting and analyzing
image EXIF metadata (camera information, GPS coordinates, timestamps, etc.).

Endpoints:
  - GET  /                    - Health check
  - POST /api/extract-exif    - Upload image and get analyzed EXIF data
  - POST /api/extract-exif-json - Upload image and get full EXIF data as JSON

Features:
  - CORS enabled for frontend access (localhost:5173, localhost:3000)
  - File upload handling
  - EXIF extraction using Pillow
  - GPS coordinate conversion (DMS to decimal degrees)
  - JSON export support

Run with: uvicorn main:app --reload
API Docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from extract_exif import extract_exif, analyze_image
import json
import os
from pathlib import Path

app = FastAPI(title="GeoData API", version="1.0.0")

# Create images/control folder if it doesn't exist
IMAGES_DIR = Path(__file__).parent / "images" / "control"
IMAGES_DIR.mkdir(parents=True, exist_ok=True)

# Configure CORS (Cross-Origin Resource Sharing) middleware
# Allows frontend requests from specified origins to access backend endpoints
# Without this, browser security would block requests from frontend to backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],  # Vite and CRA default ports
    allow_credentials=True,
    allow_methods=["*"],  # Allow all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],  # Allow all headers
)

@app.get("/")
def read_root():
    """
    Health check endpoint.
    
    Simple endpoint to verify the API server is running and responding.
    Returns a message confirming the server is operational.
    
    Returns:
        dict: {"message": "GeoData API is running"}
    """
    return {"message": "GeoData API is running"}

@app.post("/api/extract-exif")
async def extract_exif_endpoint(file: UploadFile = File(...)):
    """
    Extract and analyze EXIF data from uploaded image.
    
    Accepts an image file upload, extracts all EXIF metadata using Pillow,
    and returns structured data including camera information and GPS coordinates.
    
    Process:
      1. Receive image file from client
      2. Save to backend/images folder
      3. Call analyze_image() to extract EXIF data
      4. Return analyzed data as JSON
    
    Args:
        file (UploadFile): Image file (JPEG, PNG, etc.) with EXIF data
    
    Returns:
        dict: {
            "success": bool,
            "filename": str,
            "data": {
                "camera_make": str,
                "camera_model": str,
                "datetime": str,
                "software": str,
                "gps": {"lat": float, "lon": float} or None,
                "raw_exif": dict
            },
            "error": str (if error occurred)
        }
    """
    try:
        # Read uploaded file into memory
        contents = await file.read()
        
        # Save to images folder
        temp_path = IMAGES_DIR / file.filename
        with open(temp_path, "wb") as f:
            f.write(contents)
        
        # Extract EXIF data using analyze_image() from extract_exif module
        result = analyze_image(temp_path)
        
        # Return successful response with extracted data
        return {
            "success": True,
            "filename": file.filename,
            "data": result
        }
    except Exception as e:
        # Return error response if extraction fails
        return {
            "success": False,
            "error": str(e)
        }

@app.post("/api/extract-exif-json")
async def extract_exif_json_endpoint(file: UploadFile = File(...), output_filename: str = "exif_data.json"):
    """
    Extract EXIF data and return as complete JSON file format.
    
    Similar to /api/extract-exif but returns ALL raw EXIF data in structured JSON format.
    The response includes metadata about the extraction (image path, total tags count).
    
    Process:
      1. Receive image file from client
      2. Save to backend/images folder
      3. Call extract_exif() with output_json_path to both extract and save JSON
      4. Read saved JSON file and return complete structure
    
    Args:
        file (UploadFile): Image file to analyze
        output_filename (str, optional): Name for output JSON file. Defaults to "exif_data.json"
    
    Returns:
        dict: {
            "success": bool,
            "filename": str,
            "json_file": str,
            "data": {
                "image_path": str,
                "total_tags": int,
                "exif_data": {all EXIF tags and values}
            },
            "error": str (if error occurred)
        }
    """
    try:
        print(f"\n📤 Received file: {file.filename}")
        # Read uploaded file into memory
        contents = await file.read()
        print(f"📊 File size: {len(contents)} bytes")
        
        # Save to images folder
        temp_path = IMAGES_DIR / file.filename
        with open(temp_path, "wb") as f:
            f.write(contents)
        print(f"💾 Saved to: {temp_path}")
        
        # Extract EXIF to JSON file
        # extract_exif() saves JSON when output_json_path is provided
        json_output_path = IMAGES_DIR / output_filename
        print(f"📝 JSON will be saved to: {json_output_path}")
        exif_data = extract_exif(str(temp_path), str(json_output_path))
        print(f"✅ EXIF extracted, tags found: {len(exif_data)}")
        
        # Read the generated JSON file and return its contents
        with open(str(json_output_path), 'r') as f:
            json_data = json.load(f)
        print(f"📄 JSON file read successfully")
        
        # Return successful response with JSON data
        return {
            "success": True,
            "filename": file.filename,
            "json_file": output_filename,
            "json_path": str(json_output_path),
            "data": json_data
        }
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        # Return error response if extraction fails
        return {
            "success": False,
            "error": str(e)
        }

if __name__ == "__main__":
    # Run the FastAPI server directly (for development)
    # In production, use: uvicorn main:app --host 0.0.0.0 --port 8000
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
